### ISSUE TITLE
Webhooks are preserved after uninstall/reinstall of Kabanero, but they don't work

### ISSUE THREAD

**Issue by japerry-ibm** [kabanero-io/kabanero-foundation#146] opened 2019-12-06 19:40 UTC
The Kabanero 0.3.0 uninstall process does not remove secrets, webhooks, and pipeline runs. When a new Kabanero driver is installed, the secrets and webhooks show up in the Tekton dashboard, but they do not work. When my application is updated on github, the webhook does not initiate a pipeline run.

Should these resources be removed when Kabanero is uninstalled?

If uninstall is intentionally leaving these resources, they should work when Kabanero is reinstalled.

**Comment by gecock** [comment] 2019-12-09 19:29
@stevekinder-ibm Could you provide your input here on expected behavior of the uninstaller? There's either a big here to clean up everything properly, or there is a bug to ensure the user created resources that get left around continue to work on a new install of Kabanero.

**Comment by marikaj123** [comment] 2019-12-10 19:49
Looking to be fixed in Kabanero 0.5.0.

**Comment by stephenkinder** [comment] 2019-12-10 20:26
Well, not exactly @marikaj123.  What I said is we would not fix this in 0.3.0, if we fix anything it would be in 0.5.0 or later.  That said:

1) We are moving our implementation away from the Tekton webhook technology which relies on Knative towards Tekton Triggers.   The Tekton webhooks are unknown to the Tekton operator however we expect that the Dashboard and extension will be included at some point in the future.   Thinking it is more appropriate to get an answer from the Tekton team if it is reasonable to think that existing webhooks would be reused -- I could see value in "reviving" the webhook since it represents that there is a webhook installed in GitHub.  

2) Pipeline Runs has the status of the prior executions, wondering if we should consider optional deletions of the residual pipeline runs, however, this could be tricky if the Kabanero CR was modified several times to update pipelines; the Kabanero operator would remove the old pipelines, but purposefully not the Pipeline runs.  By the time you uninstall the operator, we may not remember all the previous pipelines.  Would you want to uninstall pipeline runs in the Kabanero namespace?  I'm thinking we might need this to be optional.

**Comment by marikaj123** [comment] 2019-12-16 18:21
@anneqm - We would like guidance from your team to look at item 1 above.

**Comment by dibbles** [comment] 2019-12-17 09:42
Regarding Tekton webhooks extension....

Personally I think whether or not an old webhook will work will depend on backwards compatibility of the Tekton code.  We likely need to do better at documenting in the release notes of Tekton the incompatibilities between versions and any migration actions necessary.  As with all new technologies, breaking changes should become less evident as time progresses - I believe in all releases thus far it has been necessary to delete and recreate the webhooks.

The artefact that remain in earlier installs of the webhooks-extension is a config map called githubwebhooks (and the webhooks in github itself) - as of 0.3.0 of tekton dashboard and webhooks the configmap is no longer used, and the required data is instead stored inside of a Tekton Triggers artefact called an Eventlistener - In theory, deleting Tekton Triggers would delete the eventlistener and as such the only artefact that would remain is the webhook in github itself.
Installing a new tekton would not automatically be able to be used by the webhook in github as no eventlistener would exist to handle the requests.

Secrets will be left behind as there is no way to know that they are not being used for other purposes.  Someone could open an issue against Tekton webhooks-extension in https://github.com/tektoncd/experimental/ to look at the possiblity of cleaning up better during uninstall but I cannot comment on its priority as a work item.

**Comment by anneqm** [comment] 2019-12-18 15:06
@marikaj123 @stephenkinder Please let us know if anything else is needed from the Tekton team at this time.   Thank you. See Duane's response to item 1 ^^.

**Comment by anneqm** [comment] 2019-12-18 22:19
We did determine that it will be necessary to delete and recreate the webhooks in the upgrade from kabanero 0.4.0 to 0.5.0.  Accordingly, how to delete webhooks has been documented in the recently published update to this document: https://kabanero.io/docs/ref/general/configuration/tekton-webhooks.html.

**Comment by marikaj123** [comment] 2020-01-08 16:57
@dacleyra - We decided the uninstall script to delete the established webhook to make it more user experience friendly.

**Comment by marikaj123** [comment] 2020-01-20 20:06
The uninstall is specific to Kabanero, does not effect other products.

**Comment by dacleyra** [comment] 2020-01-23 20:39
merged, closing

**Closed by dacleyra** 2020-01-23 20:39 UTC
Labels: bug, svt
