### ISSUE TITLE
Webhooks created in Tekton dashboard but not created in Github 

### ISSUE THREAD

**Issue by bconey** [kabanero-io/kabanero-foundation#130] opened 2019-11-13 20:56 UTC
- Installed Kabanero 0.3 on OCP4.2
- Created a default kabanero instance
- Accessed the Tekton dashboard 
- Created the appropriate secrets for github and docker
- Created a webhook for an existing sample application - Tekton dashboard indicates the webhook was created
- Accessed the github repository for the sample application and viewed the Hooks setting and the hook was not created there

**Comment by a-roberts** [comment] 2019-11-13 21:15
Can you please check the install namespace for the webhooks extension is in the servicemeshmemberroll?

If it is you want to look for logs in the GitHub controller manager pod sitting in knarive-eventing, if it's in the roll you'll see an attempt to create the webhook by the reconciler assuming you have a good looking githubsource

**Comment by bconey** [comment] 2019-11-13 22:50
Webhooks extension is in the tekton-pipelines namespace.  When doing an `oc edit -n istio-system servicemeshmemberroll default`, tekton-pipelines is showing up in the info returned...

```
spec:
  members:
  - knative-serving
  - tekton-pipelines
  - kabanero
status:
  configuredMembers:
  - kabanero
  - knative-serving
  - tekton-pipelines
```

There is a github controller manager pod is knative-source, but the logs begin

```
2019/11/13 16:54:27 Registering Components.
2019/11/13 16:54:27 Adding the GitHub Source controller.
2019/11/13 16:54:27 Starting the Cmd.
{"level":"info","ts":"2019-11-13T16:54:27.919Z","caller":"sdk/reconciler.go:53","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} tekton-pipelines/tekton-6tp8p","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-6tp8p"}
{"level":"warn","ts":"2019-11-13T16:54:28.432Z","caller":"sdk/reconciler.go:76","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: sink \"tekton-pipelines/webhooks-extension-sink\" (serving.knative.dev/v1alpha1, Kind=Service) does not contain address","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-6tp8p"}
{"level":"info","ts":"2019-11-13T16:54:29.436Z","caller":"sdk/reconciler.go:53","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} tekton-pipelines/tekton-9ssnv","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-9ssnv"}
{"level":"warn","ts":"2019-11-13T16:54:29.452Z","caller":"sdk/reconciler.go:76","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: sink \"tekton-pipelines/webhooks-extension-sink\" (serving.knative.dev/v1alpha1, Kind=Service) does not contain address","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-9ssnv"}
```
and those info/warn messages are repeated about every 4 minutes or so ...

**Comment by a-roberts** [comment] 2019-11-14 11:10
@bconey where it mentions the address can you check you've got a `ksvc` with a valid IP address set? It should automatically have resolved to be the openshift cluster's default subdomain (we don't need to manually edit config-domain in knative-serving with the Serverless Operator), that's worth checking.

Please also check you've got a githubsource with no errors reported in its status

**Comment by bconey** [comment] 2019-11-14 15:52
```
oc get ksvc
NAME                      URL                                                                           LATESTCREATED                   LATESTREADY   READY   REASON
webhooks-extension-sink   http://webhooks-extension-sink.tekton-pipelines.apps.gloomy.os.fyre.ibm.com   webhooks-extension-sink-24dbz                 False   RevisionMissing
```

[githubsource-output.txt](https://github.com/kabanero-io/kabanero-foundation/files/3847081/githubsource-output.txt)
[ksvc-output.txt](https://github.com/kabanero-io/kabanero-foundation/files/3847080/ksvc-output.txt)
[revision-output.txt](https://github.com/kabanero-io/kabanero-foundation/files/3847079/revision-output.txt)

**Comment by akihikokuroda** [comment] 2019-11-14 23:25
I'm not sure 🤔 but this may be the next clue.
```
    Last Transition Time:  2019-11-13T14:53:59Z
    Message:               Revision "webhooks-extension-sink-24dbz" failed with message: Container failed with: {"level":"info","msg":"constructed a logger"}
{"level":"info","msg":"constructed a logger"}
{"level":"info","msg":"Creating server and entering wait loop."}
.
```

**Comment by a-roberts** [comment] 2019-11-15 10:20
I'm unable to reproduce this with my working set up so I'm running the latest Kab rc3 installation script against a new cluster.

There's a chain of Knative resources to look at so I'll get on the case once my install's all done (this script takes a while and both @bconey and I noticed problems involving the ES InstallPlan).

**Comment by a-roberts** [comment] 2019-11-15 13:18
Got a new cluster and set up now (the rc3 install script worked perfectly this time around) so going for the reproduce.

**Comment by a-roberts** [comment] 2019-11-15 13:40
My first webhook failed (imagepullbackoff for the sink pod) - thus the revision was never ready for a required resource (the sink to use for the githubsource) and therefore the controller never tried to make the webhook on ghe

Deleted that, created another, green webhook made

**Comment by marikaj123** [comment] 2019-11-15 15:14
In progress

**Comment by aadeshpa** [comment] 2019-11-15 17:06
@a-roberts : I was able to get the webhook created after two or three tries. However  it shows exclamatory mark , and when i create a new pull request it does not kickoff the pipeline . Also we verified in our pod list and there is no webhook pod with `sink` name. 
<img width="1093" alt="Screen Shot 2019-11-15 at 12 05 46 PM" src="https://user-images.githubusercontent.com/53223993/68961393-49a60400-07a0-11ea-8050-7d1eaa0d8355.png">

**Comment by a-roberts** [comment] 2019-11-15 17:10
Thanks @aadeshpa, so if you click that do you get a 503 perhaps, and then a redeliver is good?

If you get a 503 it likely mentions the service is not available or serving any endpoints, indicating the sink isn't yet ready

**Comment by bconey** [comment] 2019-11-15 19:48
@a-roberts worked with me for a while on this and attempted to do the webhook deletes that he noted in recent comments but without success.  What we did see was that the webhooks-extension-sink service did not appear to be starting properly.  He said that the sink would need to be ready for webhooks to be created.  Suggestion was to try installing rc3.

Uninstalled rc2 (took a couple of runs) and then installed rc3 successfully (2 runs of the script) and verified that the sink this time was in Ready state.  Created an instance and then proceeded to create a webhook via the Tekton dashboard and this time it did show up in the github hook settings for the repository.

**Comment by anneqm** [comment] 2019-11-18 13:33
@marikaj123 @a-roberts @bconey Can this issue be closed?

**Comment by gecock** [comment] 2019-11-18 14:28
Was there a fix for this that went into rc3 or is is this working through workarounds? If I'm following the workaround is to delete the sink pod until it recreates in ready state?

At the very minimum this should be documented in the troubleshooting page.

Is there an actual fix to be had here?

**Comment by a-roberts** [comment] 2019-11-18 15:17
> Was there a fix for this that went into rc3 or is this working through workarounds? If I'm following the workaround is to delete the sink pod until it recreates in ready state?
> 
> At the very minimum this should be documented in the troubleshooting page.
> 
> Is there an actual fix to be had here?

You're right, I think there's something to document. So here's my first pass (bear in mind it's "from the developer's mouth" 😆 and ID taking a look would be welcome). Either way, lemme know.

**My webhooks aren't created on GitHub**

A scenario exists where webhook will be created on GitHub. 

**Explanation:**

On particularly slow systems or systems running under a slow network, the webhooks extension sink has been known to not be running for a considerable period of time and thus the KService is never marked as ready and the webhook is never created.

**Diagnosis:**

1. Before you do anything, check that your pods in `knative-serving`, `knative-sources,` knative-eventing` and `istio-system` are healthy, and that you have a ServiceMeshMemberRoll which *includes your install namespace for the Tekton Dashboard and Webhooks Extension*.

2. The first logs to look at are in the `github-controller-manager-0` pod in the `knative-eventing` namespace (this is where creation attempts are recorded and errors go).

A command you will find useful is:
`oc logs github-controller-manager-0  -n knative-sources | grep -i 'creating GitHub webhook' -C 3`

3. The next thing to check is for multiple "Ready" KServices.

A command to check if you have ready KServices is:

`oc get ksvc -n *my install namespace*`.

You should see output similar to this but with different exact pod names;

```
mylaptop:config myusername$ oc get ksvc
NAME                      URL                                                                         LATESTCREATED                   LATESTREADY                     READY     REASON
tekton-8hmwh-brxps        http://tekton-8hmwh-brxps.mynamespace.apps.mysystem.com        tekton-8hmwh-brxps-pj5jx        tekton-8hmwh-brxps-pj5jx        True      
webhooks-extension-sink   http://webhooks-extension-sink.mynamespace.apps.mysystem.com   webhooks-extension-sink-5tx7l   webhooks-extension-sink-5tx7l   True      
```

If you don't, it is advised to `oc describe` the KService that is not marked as being `Ready`, and to describe your `GitHubSource` to check that looks good too.

An ideal `oc describe githubsource` will include:

```
  Sink:
    API Version:  serving.knative.dev/v1alpha1
    Kind:         Service
    Name:         webhooks-extension-sink
Status:
  Conditions:
    Last Transition Time:  2019-11-15T14:19:51Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2019-11-15T14:19:51Z
    Status:                True
    Type:                  SecretsProvided
    Last Transition Time:  2019-11-15T14:19:51Z
    Status:                True
    Type:                  SinkProvided
  Sink Uri:                http://webhooks-extension-sink.myinstallnamespacesvc.cluster.local
```

If the data you see does not look like this and you consistently see this behaviour, this indicates an issue with the webhooks extension code itself.

**Comment by gecock** [comment] 2019-11-18 19:20
Thanks @a-roberts for the diagnosis information. What is still tripping me up is the suggested actions someone should take if they determine that their issue is in fact this one. You mentioned slow systems or slow networks, are you saying there is no fix to be had here from Tekton and if someone hits this issue they need to address their system/network performance issues?

**Comment by a-roberts** [comment] 2019-11-19 08:54
> Thanks @a-roberts for the diagnosis information. What is still tripping me up is the suggested actions someone should take if they determine that their issue is in fact this one. You mentioned slow systems or slow networks, are you saying there is no fix to be had here from Tekton and if someone hits this issue they need to address their system/network performance issues?

Yeah I realise it's not the best, I've been searching for annotations/configurations around timeouts we can set to avoid this problem - will ask in knative.slack.com and see if we can find something better (I basically don't think we have any code changes to make, it's just a problem seen when the sink doesn't come up and so revisions don't get marked as ready).

I'll have another good investigation today and report back.

**Comment by a-roberts** [comment] 2019-11-19 14:07
With Kab RC4 on two fresh new clusters, and a colleague doing the same thing, we're unable to reproduce the problem now.

Specifically I see an unready ksvc until the tekton-xxxxx pod runs to completion, it then becomes ready and the webhook is made. The fact it's red on initial startup (and not a green tick) is a known documented issue that folks would need to redeliver for it to be green - but in reality if they were to push or interact with the webhook anyway, all would be well as that's just for the initial ping.

**Comment by anneqm** [comment] 2019-11-19 15:54
@gecock Anything else needed to close this one?

**Comment by bconey** [comment] 2019-11-19 16:44
Uninstalled 0.3.0-rc.3 and reinstalled 0.3.0-rc.4 and the webhooks-extension-sink service started fine and webhooks were created in Github the first time with no issues.  

Closing this issue.

**Comment by mtamboli** [comment] 2019-12-09 02:48
I am re-opening this issue as I am seeing the same problem again using 0.3.3 Kabanero release where webhook is not created in GitHub. I used the above suggested debugging and it seems like my Kservice is not marked ready. How do I fix this? I restarted all pods in Tekton-pipeline namespace.

```
oc get ksvc -n tekton-pipelines
NAME                      URL                                                                        LATESTCREATED                   LATESTREADY   READY     REASON
webhooks-extension-sink   http://webhooks-extension-sink.tekton-pipelines.apps.mst.os.fyre.ibm.com   webhooks-extension-sink-4582m                 Unknown   RevisionMissing
```

```
 oc get pods
NAME                                                       READY     STATUS    RESTARTS   AGE
tekton-dashboard-6c4688f8bb-24bnw                          2/2       Running   0          2m31s
webhooks-extension-759b88f858-l8tk4                        1/1       Running   0          7m28s
webhooks-extension-sink-4582m-deployment-897dd7b86-gnmlp   2/2       Running   0          8m39s
```

**Comment by mtamboli** [comment] 2019-12-09 02:57
oc logs github-controller-manager-0 -n knative-sources
{"level":"info","ts":"2019-12-09T02:04:17.996Z","caller":"sdk/reconciler.go:53","msg":"Reconciling &TypeMeta{Kind:,APIVersion:,} tekton-pipelines/tekton-fsngb","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-fsngb"}
{"level":"warn","ts":"2019-12-09T02:04:18.025Z","caller":"sdk/reconciler.go:76","msg":"Failed to reconcile &TypeMeta{Kind:,APIVersion:,}: Internal error occurred: failed calling webhook \"webhook.serving.knative.dev\": Post https://webhook.knative-serving.svc:443/?timeout=30s: no endpoints available for service \"webhook\"","knative.dev/controller":"github-controller-manager","request":"tekton-pipelines/tekton-fsngb"} (edited)

**Comment by a-roberts** [comment] 2019-12-09 09:00
Hi @mtamboli, hmm so what exactly is installed in 0.3.3? Do things still work in 0.3.2 on your cluster? 

I'll give it a go on a new cluster today, I know you're seeing the same side effect but not a fan of using this issue perpetually (and me being forever being assigned!) when we've had a known working set up at least once on older Kabanero versions, so let's see what's different and perhaps we need to pin something else down

**Comment by mtamboli** [comment] 2019-12-09 11:56
@a-roberts I think this is an intermittent problem. We do not know what exactly cause this. We have this on and off especially if you uninstall and then install Kabanero. It may not be unique to 0.3.3.

**Comment by a-roberts** [comment] 2019-12-09 13:18
> @a-roberts I think this is an intermittent problem. We do not know what exactly cause this. We have this on and off especially if you uninstall and then install Kabanero. It may not be unique to 0.3.3.

Ah, I see, well we're in the process of publishing our 0.3.0 release for the dashboard and webhooks extension now whereby this issue is definitely resolved (owing to our move off of Istio and Knative), that's the definite fix and then it'll be up to yourselves to update the pipelines/operator and make the shift over (see https://github.com/kabanero-io/kabanero-foundation/issues/140)

**Comment by marikaj123** [comment] 2019-12-09 18:13
Accroding to @a-roberts, the proposed fix/workaround is to use the tekton dashboard 0.3.  This requires tekton triggers 0.1.  The pipelines are working to include it towards  Kabanero 0.5 or 0.6

**Comment by gecock** [comment] 2019-12-09 20:44
This may be fixed in later releases, but we need a workaround and documentation for people hitting this today with current Kabanero releases. Unless I've missed something here, there is a lot of good information about finding out _if_ you are in this error state, but there is nothing saying how to get out of that error state.

**Comment by gecock** [comment] 2019-12-09 20:57
@kaczyns your name bubbled up as someone that could have input into the necessary config/doc needed here

**Comment by jgawor** [comment] 2019-12-10 04:55
I believe I was able to get out of the error state by doing the following:
* ensure that `ServiceMeshControlPlane` is in `Ready` state
  * checked via `oc -n istio-system describe ServiceMeshControlPlane basic-install`
  * in my case, it wasn't and I was able to get it back to `Ready` by restarting all pods in the `istio-system` namespace
* ensure that `KnativeServing` is in `Ready` state
  * checked via `oc -n knative-serving describe KnativeServing knative-serving`
  * in my case, it wasn't and I was able to get it back to `Ready` by restarting all pods in the `knative-serving` namespace
* ensure that `webhooks-extension-sink` kservice is in `Ready` state
  * checked via `oc get kservice -n tekton-pipelines`
  * in my case, it wasn't and I was able to get it back to `Ready` by deleting a revision object associated with the `webhooks-extension-sink`
     * via `oc delete rev -l serving.knative.dev/configuration=webhooks-extension-sink`

These steps might be case specific but might provide another set of things to look at.

**Comment by a-roberts** [comment] 2019-12-10 09:34
> This may be fixed in later releases, but we need a workaround and documentation for people hitting this today with current Kabanero releases. Unless I've missed something here, there is a lot of good information about finding out _if_ you are in this error state, but there is nothing saying how to get out of that error state.

I agree, and as we can see from @jgawor's post there are plenty of moving parts so that 0.3 release can't come soon enough!

Looking into this now armed with the helpful info from Jarek using Kabanero 0.3.3.

With the set ups I've used things have worked out of the box unless there were network issues or *really* slow pulls going on, so I'll create plenty of hooks and see where I get since it really does keep popping up 😭

**Comment by a-roberts** [comment] 2019-12-10 10:16
I've done ten in a row just now, specifically

-> Run the 0.3.3 installer
-> Set up dynamic provisioning so we can get PVs
-> Create hooks using the UI
-> Redeliver whenever we get a 503

Working flow is
-> ksvc, configuration, revision all ready at the start for webhooks-extension-sink
-> Make a hook: we get one more resource of each and a githubsource

For debugging, yeah we've gotta check our Knative, Istio and ServiceMeshMemberRoll statuses and that those three resources (the ksvc, configuration, revisions) are all ready. If they're not we'll have to describe/get those resources and go from there - but again with a properly configured install this should never happen. If it does, we're on the hook for service and I've noticed there are mustgathers for Knative as part of the Kabanero project. Really can't suggest anything other than this.

**Comment by mtamboli** [comment] 2019-12-10 13:07
> I believe I was able to get out of the error state by doing the following:
> 
> * ensure that `ServiceMeshControlPlane` is in `Ready` state
>   
>   * checked via `oc -n istio-system describe ServiceMeshControlPlane basic-install`
>   * in my case, it wasn't and I was able to get it back to `Ready` by restarting all pods in the `istio-system` namespace
> * ensure that `KnativeServing` is in `Ready` state
>   
>   * checked via `oc -n knative-serving describe KnativeServing knative-serving`
>   * in my case, it wasn't and I was able to get it back to `Ready` by restarting all pods in the `knative-serving` namespace
> * ensure that `webhooks-extension-sink` kservice is in `Ready` state
>   
>   * checked via `oc get kservice -n tekton-pipelines`
>   * in my case, it wasn't and I was able to get it back to `Ready` by deleting a revision object associated with the `webhooks-extension-sink`
>     
>     * via `oc delete rev -l serving.knative.dev/configuration=webhooks-extension-sink`
> 
> These steps might be case specific but might provide another set of things to look at.

@jgawor thank you so much for help on debugging this. I saw the old webhook was created and also able to create new ones. 

@a-roberts Thanks for your continued support on this issue.

**Comment by marikaj123** [comment] 2019-12-10 17:45
Removing the stopship label since the issue is resolved with a workaround for Kabanero 0.3. The issue will be closed after a complete fix is provided.

**Comment by karimbzu** [comment] 2019-12-17 10:12
Thanks for all to share their experiences. I am facing the issue after triggering push event on github repo. The pipelinerun does not start.  Below is the output of some of the commands.
kindly give your expert opinion. thanks
#oc logs github-controller-manager-0 -n knative-source
{"level":"info","ts":"2019-12-17T10:06:20.461Z","logger":"github_controller.github-source-controller","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 346.902044ms.","knative.dev/controller":"github-source-controller","knative.dev/traceid":"4e826e99-00e3-4482-bdba-c5ebed5f4c33","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"info","ts":"2019-12-17T10:06:20.461Z","logger":"github_controller.github-source-controller.event-broadcaster","caller":"record/event.go:258","msg":"Event(v1.ObjectReference{Kind:\"GitHubSource\", Namespace:\"tekton-pipelines\", Name:\"tekton-jgk2k\", UID:\"d7103f2f-20b4-11ea-8a8d-ba451f2cb31a\", APIVersion:\"sources.eventing.knative.dev/v1alpha1\", ResourceVersion:\"69793186\", FieldPath:\"\"}): type: 'Warning' reason: 'GitHubSourceUpdateStatusFailed' Failed to update GitHubSource's status: the server could not find the requested resource (put githubsources.sources.eventing.knative.dev tekton-jgk2k)","knative.dev/controller":"github-source-controller"}
{"level":"info","ts":"2019-12-17T10:06:38.525Z","logger":"github_controller.github-source-controller","caller":"reconciler/githubsource.go:304","msg":"creating GitHub webhook","knative.dev/controller":"github-source-controller","knative.dev/traceid":"da6e8912-d455-4acd-940b-3009e75d92e8","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"info","ts":"2019-12-17T10:06:38.847Z","logger":"github_controller.github-source-controller","caller":"reconciler/webhook_client.go:71","msg":"create webhook error response:\n&{Response:0xc0010510e0 NextPage:0 PrevPage:0 FirstPage:0 LastPage:0 Rate:github.Rate{Limit:5000, Remaining:4993, Reset:github.Timestamp{2019-12-17 10:44:50 +0000 UTC}}}","knative.dev/controller":"github-source-controller","knative.dev/traceid":"da6e8912-d455-4acd-940b-3009e75d92e8","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"warn","ts":"2019-12-17T10:06:38.847Z","logger":"github_controller.github-source-controller","caller":"reconciler/githubsource.go:136","msg":"Error reconciling GitHubSource{error 25 0  failed to create webhook: failed to create the webhook: POST https://api.github.com/repos/karimbzu/kabanero-java-microprofile/hooks: 422 Validation Failed [{Resource:Hook Field: Code:custom Message:Hook already exists on this repository}]}","knative.dev/controller":"github-source-controller","knative.dev/traceid":"da6e8912-d455-4acd-940b-3009e75d92e8","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"warn","ts":"2019-12-17T10:06:38.849Z","logger":"github_controller.github-source-controller","caller":"reconciler/githubsource.go:143","msg":"Failed to update the GitHubSource{error 25 0  the server could not find the requested resource (put githubsources.sources.eventing.knative.dev tekton-jgk2k)}","knative.dev/controller":"github-source-controller","knative.dev/traceid":"da6e8912-d455-4acd-940b-3009e75d92e8","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"error","ts":"2019-12-17T10:06:38.849Z","logger":"github_controller.github-source-controller","caller":"controller/controller.go:376","msg":"Reconcile error","knative.dev/controller":"github-source-controller","error":"the server could not find the requested resource (put githubsources.sources.eventing.knative.dev tekton-jgk2k)","stacktrace":"knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).handleErr\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:376\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).processNextWorkItem\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:362\nknative.dev/eventing-contrib/vendor/knative.dev/pkg/controller.(*Impl).Run.func2\n\t/home/prow/go/src/knative.dev/eventing-contrib/vendor/knative.dev/pkg/controller/controller.go:310"}
{"level":"info","ts":"2019-12-17T10:06:38.849Z","logger":"github_controller.github-source-controller","caller":"controller/controller.go:363","msg":"Reconcile failed. Time taken: 342.660354ms.","knative.dev/controller":"github-source-controller","knative.dev/traceid":"da6e8912-d455-4acd-940b-3009e75d92e8","knative.dev/key":"tekton-pipelines/tekton-jgk2k"}
{"level":"info","ts":"2019-12-17T10:06:38.849Z","logger":"github_controller.github-source-controller.event-broadcaster","caller":"record/event.go:258","msg":"Event(v1.ObjectReference{Kind:\"GitHubSource\", Namespace:\"tekton-pipelines\", Name:\"tekton-jgk2k\", UID:\"d7103f2f-20b4-11ea-8a8d-ba451f2cb31a\", APIVersion:\"sources.eventing.knative.dev/v1alpha1\", ResourceVersion:\"69793186\", FieldPath:\"\"}): type: 'Warning' reason: 'GitHubSourceUpdateStatusFailed' Failed to update GitHubSource's status: the server could not find the requested resource (put githubsources.sources.eventing.knative.dev tekton-jgk2k)","knative.dev/controller":"github-source-controller"}
#oc get ksvc -n tekton-pipelines
NAME                      URL                                                                     LATESTCREATED                   LATESTREADY                     READY   REASON
tekton-jgk2k-cw9qd        http://tekton-jgk2k-cw9qd.tekton-pipelines.apps.ocp.tmrnd.com.my        tekton-jgk2k-cw9qd-kbwlz        tekton-jgk2k-cw9qd-kbwlz        True
tekton-xgv4l-588dt        http://tekton-xgv4l-588dt.tekton-pipelines.apps.ocp.tmrnd.com.my        tekton-xgv4l-588dt-ghqbp        tekton-xgv4l-588dt-ghqbp        True
webhooks-extension-sink   http://webhooks-extension-sink.tekton-pipelines.apps.ocp.tmrnd.com.my   webhooks-extension-sink-ddbsd   webhooks-extension-sink-ddbsd   True

**Comment by anneqm** [comment] 2019-12-18 16:15
@karimbzu  Would you please open above as a new issue? Thank you!

**Comment by anneqm** [comment] 2019-12-18 18:46
@marikaj123 any progress on who can handle this "Open a ticket to fix an issue that may be related to Service Mesh".

**Comment by karimbzu** [comment] 2019-12-19 01:41
@anneqm Thanks for your reply. I have resolved the issue by installing kabanero 0.4 on my openshift cluster. I need to ask, does Kabanero provides gitlab sources for webhook as well?

**Comment by anneqm** [comment] 2020-01-06 14:42
@karimbz As I understand it, Tekton does not yet support gitlab sources.

**Comment by marikaj123** [comment] 2020-01-09 02:32
COnfirmed with Anne, Webhooks don't support Gitlab. Closing this issue.

**Closed by marikaj123** 2020-01-09 02:32 UTC
Labels: blockedBy-Mesh Service, bug
