### ISSUE TITLE
Jane can get to Application Navigator from our unified console experience.

### ISSUE THREAD

**Issue by ralanlittle** [kabanero-io/kabanero-foundation#34] opened 2019-06-20 17:37 UTC

**Comment by cvignola** [comment] 2019-08-08 13:03
Application Navigator work tracked by this issue:  https://github.ibm.com/WASCloudPrivate/roadmap-convergence/issues/871

**Comment by ianpartridge** [comment] 2019-08-08 13:09
OK thanks, closing in favour of that issue.

**Comment by marikaj123** [comment] 2019-08-08 16:14
The collection has a dependency on https://github.ibm.com/WASCloudPrivate/roadmap-convergenc

**Comment by marikaj123** [comment] 2019-08-14 14:06
This issue should go under AppNav team.

**Comment by marikaj123** [comment] 2019-09-19 19:39
@dianak2016 - Can a release be assigned to the Epic.

**Comment by dianak2016** [comment] 2019-09-24 15:07
This is essentially a duplicate of https://github.com/kabanero-io/roadmap/issues/70 .  The epic 70 covers this and more, hence closing 34.

**Closed by dianak2016** 2019-09-24 15:07 UTC
Labels: blockedBy-AppNav
